eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

spring:
  application:
    name: mall-shopping-cart


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/djk_mall?useUnicode=true&characterEncoding=UTF-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456

mybatis:
  mapper-locations: mapper/**Mapper.xml
  configuration:
      map-underscore-to-camel-case: true


server:
  port: 8085

