eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:8080/eureka/

spring:
  application:
    name: mall-server-admin
  mail:
    host: smtp.163.com
    username: xx@163.com
    password: xx
  boot:
    admin:
      notify:
        mail:
          to: 547265436@qq.com
          from: xx@163.com

server:
  port: 8088