eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:8080/eureka/

spring:
  application:
    name: mall-zuul
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://${ZIPKIN}:9411/


server:
  port: 8081


zuul:
  routes:
    uaa:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: mall-auth
  add-proxy-headers: true
  sensitive-headers:



security:
  oauth2:
    client:
      access-token-uri: http://localhost:8081/uaa/oauth/token
      user-authorization-uri: http://localhost:8081/uaa/oauth/authorize
    resource:
      user-info-uri: http://localhost:8081/uaa/user
      prefer-token-info: false